### ISSUE TITLE
Comments are a bit hard to see in the diff editor

### ISSUE THREAD

**Issue by El-Tejaso** [raunofreiberg/vesper#1]
Comments in the diff editor are a bit hard to see:

![image](https://user-images.githubusercontent.com/45031546/219829954-8cc7f9ff-aa4c-4852-a8cf-170cac8f4357.png)
![image](https://user-images.githubusercontent.com/45031546/219829967-210c4e29-9534-4ce7-986e-dbf7953fc3be.png)

Other than that, really epic theme you've made here

**Comment by trm217** [comment]
Same issue with git-blame from the commonly used git-lens extension.

**Comment by raunofreiberg** [comment]
Should be resolved by #2
