### ISSUE TITLE
Problems parsing JSON theme file: Comma expected

### ISSUE THREAD

**Issue by shenlong616** [raunofreiberg/vesper#4]
- Please add `comma` to this line

https://github.com/raunofreiberg/vesper/blob/06ab13bebd138b5b793d87135a10e2cab4952968/themes/Vesper-dark-color-theme.json#L23

![image](https://github.com/raunofreiberg/vesper/assets/15698245/1a3ab329-6891-49a2-8fd7-5d77f7135063)

**Comment by raunofreiberg** [comment]
That was a bad version. It should be fixed already.
