### ISSUE TITLE
Zed Vesper theme

### ISSUE THREAD

**Issue by Moshyfawn** [raunofreiberg/vesper#9]
Hi, I've been enjoying Vesper in both my IDE and terminal.

The Zed editor has recently added support for both [user themes](https://zed.dev/blog/user-themes-now-in-preview#using-a-vs-code-theme) and [extensions](https://github.com/zed-industries/extensions), to which @bdsqqq has made the changes to [the Zed Vesper theme config](https://gist.github.com/bdsqqq/a54f73271bc23096e4af8daec92b9229).

I've configured [this repo](https://github.com/Moshyfawn/vesper) to follow the Zed extensions convention, and I was wondering if you'd be willing to add it to the Zed extensions repo so that everyone can download the theme in the editor.

I can easily transfer the repo to your ownership or anything else you see fit, as I have no claims on it.

Let me know what you think!

Edit: I also added you both as collaborators if you decide to go through with it.

**Comment by mypalvikram** [comment]
@Moshyfawn Can you get that theme submitted? Would love to use it in Zed.

**Comment by Moshyfawn** [comment]
> @Moshyfawn Can you get that theme submitted? Would love to use it in Zed.

[It has already been submitted](https://github.com/bdsqqq/vesper-zed) by Igor 🎉 You can find it in the Extensions tab in Zed by searching for "Vesper".

<img width="824" alt="image" src="https://github.com/raunofreiberg/vesper/assets/16290753/3988ce9b-ecab-4189-8972-bc22bba5a57b">
